# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fuente', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('codigo_sector', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre_sector', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Sit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sit', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad_Ejecutora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_unidad', models.CharField(max_length=200)),
            ],
        ),
    ]
