# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('prog', models.IntegerField()),
                ('subp', models.IntegerField()),
                ('proy', models.IntegerField()),
                ('subp2', models.IntegerField()),
                ('rec', models.IntegerField()),
                ('nombre_proyecto', models.CharField(max_length=200)),
                ('apropiacion_inicial', models.BigIntegerField()),
                ('apropiacion_vigente', models.BigIntegerField()),
                ('compromiso', models.BigIntegerField()),
                ('obligaciones', models.BigIntegerField()),
                ('pagos', models.BigIntegerField()),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedades.Fuente')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedades.Sector')),
                ('sit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedades.Sit')),
                ('unidad_ejecutora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedades.Unidad_Ejecutora')),
            ],
        ),
    ]
